# This class makes use of the code generated by PySide2 to generate it's interface.
# Once the interface is drawn, additional code can be written to fill fields in,
# adjust default values, or connect signals (events) to slots (listeners)

from PySide2 import QtWidgets
from PySide2.QtCore import Slot, QDate
from PySide2.QtWidgets import QDialog
from Screens.Interfaces.ui_sampleScreen import Ui_SampleScreen

class BHSampleScreenDialog(QDialog):
    def __init__(self):
        super(BHSampleScreenDialog, self).__init__()

        # Instantiate the ui design class generated by pyside2-uic
        # pyside2-uic sampleScreen.ui > ui_sampleScreen.py
        # remember to re-run the command on the shell after making changes to the .ui file
        self.ui = Ui_SampleScreen()

        # Call setupUi to generate interface
        self.ui.setupUi(self)

        # Fill fields
        self.ui.nameField.setText("Josh")
        self.ui.nicknameField.setText("Dr. Salamah")

        # Connect the value changed signal (event) of the slider to a slot (listener)
        self.ui.slider.valueChanged.connect(self.sliderValueChanged)

    # Slot (listener) for slider value change
    @Slot()
    def sliderValueChanged(self, value):
        self.ui.progress.setValue(value)
